import type { ImageConfig, ImageInfo } from './types';

export const mockImageConfig: ImageConfig = {
    basic: {
        brightness: 50,
        contrast: 50,
        saturation: 52,
        sharpness: 32,
        hue: 50,
    },
    exposure: {
        mode: 'auto',
        anti_flicker: '50hz',
        exposure_time: 'auto',
        gain: 'auto',
        compensation: 50,
        slow_shutter: false,
        max_exposure_time: '1/30',
    },
    white_balance: { mode: 'auto', red_gain: 50, blue_gain: 45 },
    enhancement: { denoise_2d: 60, denoise_3d: 52, defog: false, gamma: 50 },
    backlight: { mode: 'off', level: 50 },
    orientation: { mirror: false, flip: false },
    color_mode: { mode: 'color' },
    lens_correction: {
        enabled: false,
        aspect: true,
        x_ratio: 100,
        y_ratio: 100,
        xy_ratio: 100,
        center_x_offset: 0,
        center_y_offset: 0,
        distortion_ratio: 0,
    },
    stabilization: {
        enabled: false,
        motion_level: 'normal',
        crop_ratio: 80,
        buffer_frames: 6,
        frame_rate: 30,
        moving_subject_level: 0,
        rolling_shutter_coef: 0,
        horizontal_limit: 512,
        vertical_limit: 512,
    },
    strategy: { enabled: true, mode: 'low_noise' },
};

export const mockImageInfo: ImageInfo = {
    enabled: true,
    active: true,
    exposure_valid: true,
    iso: 200,
    exposure_time_us: 10000,
    analog_gain: 1024,
    digital_gain: 1024,
    isp_digital_gain: 1024,
    mode: 'low_noise',
    tier: 'day',
    saturation: 52,
    sharpness: 30,
    denoise_2d: 64,
    denoise_3d: 56,
    gamma: 50,
};
