import type {
  MediaPlaybackUrls,
  MediaSessionInfo,
  MediaStreamRuntime,
  RtspConfig,
  StreamName,
  WebrtcConfig,
  WebrtcPeerInfo,
} from './types';

export const mockRtspConfig: RtspConfig = {
  enabled: true,
  port: 554,
  auth_required: true,
  max_sessions: 8,
  session_timeout_sec: 60,
};

export const mockWebrtcConfig: WebrtcConfig = {
  enabled: true,
  ice_servers: [],
  max_peers: 4,
  prefer_tcp: false,
};

export const mockMediaStreams: MediaStreamRuntime[] = [
  {
    stream: 'main',
    available: true,
    running: true,
    codec: 'h264',
    codec_generation: 12,
    track_ready: true,
    hls_supported: true,
    hls_ready: true,
    http_flv_supported: true,
    http_flv_ready: true,
    mjpeg_supported: false,
    mjpeg_ready: false,
    webrtc_supported: true,
    webrtc_ready: true,
    reader_count: 2,
    client_count: 1,
    cached_frames: 48,
    cached_bytes: 1462272,
    hls_bytes: 3145728,
    last_dts: 63822704000,
    last_keyframe_request_ms: Date.now() - 1800,
    last_keyframe_seen_ms: Date.now() - 1500,
    last_first_frame_ms: Date.now() - 1200,
    last_protocol_ready_ms: Date.now() - 900,
    last_reset_reason: '',
    resolution: '1920x1080',
    fps: 30,
    bitrate_kbps: 12288,
  },
  {
    stream: 'sub',
    available: true,
    running: true,
    codec: 'h264',
    codec_generation: 9,
    track_ready: true,
    hls_supported: true,
    hls_ready: true,
    http_flv_supported: true,
    http_flv_ready: true,
    mjpeg_supported: false,
    mjpeg_ready: false,
    webrtc_supported: true,
    webrtc_ready: true,
    reader_count: 1,
    client_count: 1,
    cached_frames: 60,
    cached_bytes: 491520,
    hls_bytes: 524288,
    last_dts: 63822704200,
    last_keyframe_request_ms: Date.now() - 1800,
    last_keyframe_seen_ms: Date.now() - 1500,
    last_first_frame_ms: Date.now() - 1200,
    last_protocol_ready_ms: Date.now() - 900,
    last_reset_reason: '',
    resolution: '1280x720',
    fps: 30,
    bitrate_kbps: 2048,
  },
];

export const mockMediaPlaybackUrls: Record<StreamName, MediaPlaybackUrls> = {
  main: {
    stream: 'main',
    rtsp: 'rtsp://device/live/main',
    hls: '/live/main/hls/index.m3u8',
    http_flv: '/live/main.live.flv',
    mjpeg: '/live/main.mjpg',
    snapshot: '/snapshot/main.jpg',
    webrtc_whep: '/live/main/whep',
  },
  sub: {
    stream: 'sub',
    rtsp: 'rtsp://device/live/sub',
    hls: '/live/sub/hls/index.m3u8',
    http_flv: '/live/sub.live.flv',
    mjpeg: '/live/sub.mjpg',
    snapshot: '/snapshot/sub.jpg',
    webrtc_whep: '/live/sub/whep',
  },
};

export const mockMediaSessions: MediaSessionInfo[] = [
  {
    session_id: 'flv-sub-1',
    protocol: 'http_flv',
    stream: 'sub',
    state: 'streaming',
    client_ip: '192.168.1.32',
    user_name: 'admin',
    pending_bytes: 0,
    close_reason: '',
    created_at_ms: 1710000000000,
    updated_at_ms: 1710000003500,
  },
  {
    session_id: 'rtsp-main-1',
    protocol: 'rtsp',
    stream: 'main',
    state: 'playing',
    client_ip: '192.168.1.40',
    user_name: 'viewer',
    pending_bytes: 4096,
    close_reason: '',
    created_at_ms: 1710000001000,
    updated_at_ms: 1710000003600,
  },
];

export const mockWebrtcPeer = (stream: StreamName): WebrtcPeerInfo => ({
  peer_id: `mock-${stream}-${Date.now()}`,
  stream,
  codec: 'h264',
  state: 'created',
  client_id: 'web',
  session_id: 'mock-session',
  user_name: 'admin',
  client_ip: '127.0.0.1',
  ice_selected: false,
  dtls_state: 'new',
  srtp_ready: false,
  rtp_packets: 0,
  rtp_bytes: 0,
  last_error: '',
  created_at_ms: Date.now(),
  updated_at_ms: Date.now(),
});
